export const costumes = [
	// HORROR - CLASSIQUES
	{
		id: 1,
		name: "Vampire",
		category: "horror",
		difficulty: "easy",
		price_range: "low",
		description: "Classic vampire costume with cape and fangs",
		image_url: "/images/costumes/vampire.jpg",
		tags: ["blood", "cape", "fangs", "nocturnal"],
		materials: [
			{ material: "Black cape", quantity: "1" },
			{ material: "Plastic fangs", quantity: "1 set" },
			{ material: "White face paint", quantity: "1 tube" },
		],
	},
	{
		id: 2,
		name: "Zombie",
		category: "horror",
		difficulty: "easy",
		price_range: "low",
		description: "Undead zombie with torn clothes and realistic wounds",
		image_url: "/images/costumes/zombie.jpg",
		tags: ["undead", "blood", "apocalypse", "walking dead"],
		materials: [
			{ material: "Old clothes", quantity: "1 set" },
			{ material: "Fake blood", quantity: "1 bottle" },
			{ material: "Grey face paint", quantity: "1 tube" },
		],
	},
	{
		id: 3,
		name: "Frankenstein's Monster",
		category: "horror",
		difficulty: "medium",
		price_range: "medium",
		description: "The classic reanimated monster with bolts and stitches",
		image_url: "/images/costumes/frankenstein.jpg",
		tags: ["monster", "stitches", "bolts", "classic"],
		materials: [
			{ material: "Green face paint", quantity: "1 tube" },
			{ material: "Neck bolts", quantity: "2" },
			{ material: "Black wig", quantity: "1" },
		],
	},

	// FANTASY - MAGIE
	{
		id: 4,
		name: "Witch",
		category: "fantasy",
		difficulty: "medium",
		price_range: "low",
		description: "Traditional witch costume with hat and broom",
		image_url: "/images/costumes/witch.jpg",
		tags: ["broom", "hat", "magic", "cauldron"],
		materials: [
			{ material: "Witch hat", quantity: "1" },
			{ material: "Broom", quantity: "1" },
			{ material: "Black dress", quantity: "1" },
		],
	},
	{
		id: 5,
		name: "Wizard",
		category: "fantasy",
		difficulty: "medium",
		price_range: "medium",
		description: "Powerful wizard with robe, hat and magical staff",
		image_url: "/images/costumes/wizard.jpg",
		tags: ["magic", "staff", "robe", "spellbook"],
		materials: [
			{ material: "Wizard robe", quantity: "1" },
			{ material: "Pointed hat", quantity: "1" },
			{ material: "Magic staff", quantity: "1" },
		],
	},
	{
		id: 6,
		name: "Fairy",
		category: "fantasy",
		difficulty: "hard",
		price_range: "medium",
		description: "Enchanting fairy with wings and magical accessories",
		image_url: "/images/fairy.jpg",
		tags: ["wings", "sparkle", "magic", "nature"],
		materials: [
			{ material: "Fairy wings", quantity: "1 pair" },
			{ material: "Sparkly dress", quantity: "1" },
			{ material: "Magic wand", quantity: "1" },
		],
	},

	// MOVIE/TV - POP CULTURE
	{
		id: 7,
		name: "Superhero",
		category: "movie",
		difficulty: "hard",
		price_range: "high",
		description: "Custom superhero costume with cape and mask",
		image_url: "/images/costumes/superhero.jpg",
		tags: ["cape", "mask", "hero", "comics"],
		materials: [
			{ material: "Cape", quantity: "1" },
			{ material: "Mask", quantity: "1" },
			{ material: "Bodysuit", quantity: "1" },
		],
	},
	{
		id: 8,
		name: "Pirate",
		category: "movie",
		difficulty: "medium",
		price_range: "medium",
		description: "Swashbuckling pirate with eye patch and sword",
		image_url: "/images/costumes/pirate.jpg",
		tags: ["sea", "sword", "treasure", "parrot"],
		materials: [
			{ material: "Eye patch", quantity: "1" },
			{ material: "Toy sword", quantity: "1" },
			{ material: "Striped shirt", quantity: "1" },
		],
	},
	{
		id: 9,
		name: "Astronaut",
		category: "movie",
		difficulty: "hard",
		price_range: "high",
		description: "Space explorer with helmet and NASA-style suit",
		image_url: "/images/costumes/astronaut.jpg",
		tags: ["space", "nasa", "moon", "explorer"],
		materials: [
			{ material: "Space helmet", quantity: "1" },
			{ material: "White bodysuit", quantity: "1" },
			{ material: "Oxygen tank", quantity: "1" },
		],
	},

	// ANIMALS - ADORABLES
	{
		id: 10,
		name: "Cat",
		category: "animal",
		difficulty: "easy",
		price_range: "low",
		description: "Playful cat with ears, tail and whiskers",
		image_url: "/images/costumes/cat.jpg",
		tags: ["whiskers", "tail", "ears", "playful"],
		materials: [
			{ material: "Cat ears", quantity: "1 pair" },
			{ material: "Tail", quantity: "1" },
			{ material: "Black leotard", quantity: "1" },
		],
	},
	{
		id: 11,
		name: "Lion",
		category: "animal",
		difficulty: "medium",
		price_range: "medium",
		description: "King of the jungle with majestic mane",
		image_url: "/images/lion.jpg",
		tags: ["majestic", "wild", "king", "safari"],
		materials: [
			{ material: "Lion mane", quantity: "1" },
			{ material: "Brown bodysuit", quantity: "1" },
			{ material: "Face paint", quantity: "1 set" },
		],
	},
	{
		id: 12,
		name: "Butterfly",
		category: "animal",
		difficulty: "medium",
		price_range: "medium",
		description: "Colorful butterfly with delicate wings",
		image_url: "/images/butterfly.jpg",
		tags: ["wings", "colorful", "delicate", "spring"],
		materials: [
			{ material: "Butterfly wings", quantity: "1 pair" },
			{ material: "Colorful dress", quantity: "1" },
			{ material: "Antenna headband", quantity: "1" },
		],
	},

	// PROFESSIONNELS - MÉTIERS
	{
		id: 13,
		name: "Doctor",
		category: "professional",
		difficulty: "easy",
		price_range: "low",
		description: "Medical professional with lab coat and stethoscope",
		image_url: "/images/doctor.jpg",
		tags: ["medical", "stethoscope", "lab coat", "health"],
		materials: [
			{ material: "White lab coat", quantity: "1" },
			{ material: "Stethoscope", quantity: "1" },
			{ material: "Face mask", quantity: "1" },
		],
	},
	{
		id: 14,
		name: "Firefighter",
		category: "professional",
		difficulty: "medium",
		price_range: "medium",
		description: "Brave firefighter with helmet and jacket",
		image_url: "/images/firefighter.jpg",
		tags: ["hero", "fire", "helmet", "rescue"],
		materials: [
			{ material: "Firefighter helmet", quantity: "1" },
			{ material: "Yellow jacket", quantity: "1" },
			{ material: "Hose", quantity: "1" },
		],
	},
	{
		id: 15,
		name: "Chef",
		category: "professional",
		difficulty: "easy",
		price_range: "low",
		description: "Professional chef with hat and apron",
		image_url: "/images/chef.jpg",
		tags: ["cooking", "food", "apron", "kitchen"],
		materials: [
			{ material: "Chef hat", quantity: "1" },
			{ material: "White apron", quantity: "1" },
			{ material: "Wooden spoon", quantity: "1" },
		],
	},

	// HISTORIQUE - ÉPOQUES
	{
		id: 16,
		name: "Medieval Knight",
		category: "historical",
		difficulty: "hard",
		price_range: "high",
		description: "Brave knight in shining armor with sword and shield",
		image_url: "/images/knight.jpg",
		tags: ["armor", "sword", "shield", "castle"],
		materials: [
			{ material: "Armor set", quantity: "1" },
			{ material: "Sword", quantity: "1" },
			{ material: "Shield", quantity: "1" },
		],
	},
	{
		id: 17,
		name: "Egyptian Pharaoh",
		category: "historical",
		difficulty: "medium",
		price_range: "medium",
		description: "Ancient Egyptian ruler with headdress and accessories",
		image_url: "/images/pharaoh.jpg",
		tags: ["egypt", "pyramid", "gold", "ancient"],
		materials: [
			{ material: "Pharaoh headdress", quantity: "1" },
			{ material: "White linen", quantity: "2 meters" },
			{ material: "Gold jewelry", quantity: "set" },
		],
	},
	{
		id: 18,
		name: "1920s Flapper",
		category: "historical",
		difficulty: "medium",
		price_range: "medium",
		description: "Roaring twenties dancer with fringe dress and headband",
		image_url: "/images/flapper.jpg",
		tags: ["1920s", "jazz", "fringe", "great gatsby"],
		materials: [
			{ material: "Fringe dress", quantity: "1" },
			{ material: "Feather headband", quantity: "1" },
			{ material: "Long pearls", quantity: "1 strand" },
		],
	},

	// CREATURES MYTHIQUES
	{
		id: 19,
		name: "Mermaid",
		category: "fantasy",
		difficulty: "hard",
		price_range: "high",
		description: "Mystical mermaid with shimmering tail",
		image_url: "/images/mermaid.jpg",
		tags: ["ocean", "tail", "scales", "underwater"],
		materials: [
			{ material: "Mermaid tail", quantity: "1" },
			{ material: "Seashell top", quantity: "1" },
			{ material: "Shimmery makeup", quantity: "set" },
		],
	},
	{
		id: 20,
		name: "Unicorn",
		category: "fantasy",
		difficulty: "medium",
		price_range: "medium",
		description: "Magical unicorn with horn and rainbow colors",
		image_url: "/images/unicorn.jpg",
		tags: ["rainbow", "horn", "magical", "sparkle"],
		materials: [
			{ material: "Unicorn horn", quantity: "1" },
			{ material: "Rainbow wig", quantity: "1" },
			{ material: "Sparkly tutu", quantity: "1" },
		],
	},
	{
		id: 21,
		name: "Dragon",
		category: "fantasy",
		difficulty: "hard",
		price_range: "high",
		description: "Fierce dragon with wings and scales",
		image_url: "/images/dragon.jpg",
		tags: ["fire", "wings", "scales", "mythical"],
		materials: [
			{ material: "Dragon mask", quantity: "1" },
			{ material: "Wings", quantity: "1 pair" },
			{ material: "Scale pattern bodysuit", quantity: "1" },
		],
	},

	// HUMOUR - DÉLICIEUSEMENT DRÔLE
	{
		id: 22,
		name: "Taco",
		category: "funny",
		difficulty: "medium",
		price_range: "medium",
		description: "Delicious walking taco costume",
		image_url: "/images/taco.jpg",
		tags: ["food", "mexican", "funny", "delicious"],
		materials: [
			{ material: "Brown bodysuit", quantity: "1" },
			{ material: "Felt ingredients", quantity: "set" },
			{ material: "Lettuce fringe", quantity: "1" },
		],
	},
	{
		id: 23,
		name: "Inflatable Dinosaur",
		category: "funny",
		difficulty: "easy",
		price_range: "medium",
		description: "Giant inflatable T-Rex costume",
		image_url: "/images/dinosaur.jpg",
		tags: ["giant", "inflatable", "prehistoric", "funny"],
		materials: [
			{ material: "Inflatable costume", quantity: "1" },
			{ material: "Battery pack", quantity: "1" },
			{ material: "Small fan", quantity: "1" },
		],
	},
	{
		id: 24,
		name: "Banana",
		category: "funny",
		difficulty: "easy",
		price_range: "low",
		description: "Simple yet hilarious banana costume",
		image_url: "/images/banana.jpg",
		tags: ["fruit", "yellow", "simple", "funny"],
		materials: [
			{ material: "Banana costume", quantity: "1" },
			{ material: "Yellow tights", quantity: "1 pair" },
		],
	},

	// SUPER-HÉROS SPÉCIFIQUES
	{
		id: 25,
		name: "Spider-Man",
		category: "movie",
		difficulty: "medium",
		price_range: "medium",
		description: "Friendly neighborhood Spider-Man",
		image_url: "/images/spiderman.jpg",
		tags: ["marvel", "web", "superhero", "comics"],
		materials: [
			{ material: "Spider-Man suit", quantity: "1" },
			{ material: "Web shooter", quantity: "2" },
			{ material: "Mask", quantity: "1" },
		],
	},
	{
		id: 26,
		name: "Batman",
		category: "movie",
		difficulty: "hard",
		price_range: "high",
		description: "Dark knight crime fighter",
		image_url: "/images/batman.jpg",
		tags: ["dc", "cape", "cowl", "superhero"],
		materials: [
			{ material: "Batsuit", quantity: "1" },
			{ material: "Cape", quantity: "1" },
			{ material: "Utility belt", quantity: "1" },
		],
	},
	{
		id: 27,
		name: "Wonder Woman",
		category: "movie",
		difficulty: "medium",
		price_range: "medium",
		description: "Amazonian warrior princess",
		image_url: "/images/wonderwoman.jpg",
		tags: ["dc", "amazon", "warrior", "superhero"],
		materials: [
			{ material: "Bodice and skirt", quantity: "1 set" },
			{ material: "Tiara", quantity: "1" },
			{ material: "Lasso of truth", quantity: "1" },
		],
	},

	// PERSONNAGES DE JEUX VIDÉO
	{
		id: 28,
		name: "Mario",
		category: "movie",
		difficulty: "easy",
		price_range: "low",
		description: "Italian plumber from the Mushroom Kingdom",
		image_url: "/images/mario.jpg",
		tags: ["nintendo", "plumber", "video game", "mustache"],
		materials: [
			{ material: "Red cap", quantity: "1" },
			{ material: "Overalls", quantity: "1" },
			{ material: "Fake mustache", quantity: "1" },
		],
	},
	{
		id: 29,
		name: "Lara Croft",
		category: "movie",
		difficulty: "medium",
		price_range: "medium",
		description: "Tomb Raider adventurer",
		image_url: "/images/laracroft.jpg",
		tags: ["adventure", "archaeologist", "video game", "action"],
		materials: [
			{ material: "Tank top", quantity: "1" },
			{ material: "Shorts", quantity: "1" },
			{ material: "Holster", quantity: "2" },
		],
	},
	{
		id: 30,
		name: "Among Us Character",
		category: "movie",
		difficulty: "easy",
		price_range: "low",
		description: "Suspicious space crewmate",
		image_url: "/images/amongus.jpg",
		tags: ["video game", "space", "impostor", "simple"],
		materials: [
			{ material: "Colored bodysuit", quantity: "1" },
			{ material: "Backpack", quantity: "1" },
			{ material: "Visor", quantity: "1" },
		],
	},

	// MONSTRES MODERNES
	{
		id: 31,
		name: "Slender Man",
		category: "horror",
		difficulty: "easy",
		price_range: "low",
		description: "Internet urban legend tall man",
		image_url: "/images/slenderman.jpg",
		tags: ["internet", "tall", "suit", "creepy"],
		materials: [
			{ material: "Black suit", quantity: "1" },
			{ material: "White mask", quantity: "1" },
			{ material: "Tentacle extensions", quantity: "4-8" },
		],
	},
	{
		id: 32,
		name: "Demogorgon",
		category: "horror",
		difficulty: "hard",
		price_range: "high",
		description: "Stranger Things otherworldly creature",
		image_url: "/images/demogorgon.jpg",
		tags: ["stranger things", "flower face", "monster", "upside down"],
		materials: [
			{ material: "Monster mask", quantity: "1" },
			{ material: "Bodysuit", quantity: "1" },
			{ material: "Prosthetic pieces", quantity: "set" },
		],
	},

	// ANIMALS - PLUS D'OPTIONS
	{
		id: 33,
		name: "Panda",
		category: "animal",
		difficulty: "medium",
		price_range: "medium",
		description: "Cute black and white bamboo lover",
		image_url: "/images/panda.jpg",
		tags: ["bamboo", "cute", "black and white", "china"],
		materials: [
			{ material: "Panda hoodie", quantity: "1" },
			{ material: "Black leggings", quantity: "1 pair" },
			{ material: "Bamboo stick", quantity: "1" },
		],
	},
	{
		id: 34,
		name: "Bee",
		category: "animal",
		difficulty: "easy",
		price_range: "low",
		description: "Buzzing bee with stripes and wings",
		image_url: "/images/bee.jpg",
		tags: ["insect", "stripes", "wings", "honey"],
		materials: [
			{ material: "Black and yellow stripes", quantity: "1" },
			{ material: "Bee wings", quantity: "1 pair" },
			{ material: "Antenna headband", quantity: "1" },
		],
	},

	// FANTASY - ADDITIONNEL
	{
		id: 35,
		name: "Elf",
		category: "fantasy",
		difficulty: "medium",
		price_range: "medium",
		description: "Woodland elf with pointy ears and nature elements",
		image_url: "/images/elf.jpg",
		tags: ["forest", "pointy ears", "nature", "magical"],
		materials: [
			{ material: "Pointy ears", quantity: "1 pair" },
			{ material: "Green tunic", quantity: "1" },
			{ material: "Bow and arrow", quantity: "1 set" },
		],
	},
	{
		id: 36,
		name: "Dwarf",
		category: "fantasy",
		difficulty: "medium",
		price_range: "medium",
		description: "Stout dwarf with beard and axe",
		image_url: "/images/dwarf.jpg",
		tags: ["beard", "axe", "mining", "strong"],
		materials: [
			{ material: "Fake beard", quantity: "1" },
			{ material: "Axe", quantity: "1" },
			{ material: "Helmet", quantity: "1" },
		],
	},

	// HISTORIQUE - SUPPLEMENT
	{
		id: 37,
		name: "Roman Gladiator",
		category: "historical",
		difficulty: "medium",
		price_range: "medium",
		description: "Ancient Roman warrior with armor and helmet",
		image_url: "/images/gladiator.jpg",
		tags: ["rome", "colosseum", "warrior", "sandals"],
		materials: [
			{ material: "Armor pieces", quantity: "set" },
			{ material: "Helmet", quantity: "1" },
			{ material: "Sword", quantity: "1" },
		],
	},
	{
		id: 38,
		name: "Victorian Lady",
		category: "historical",
		difficulty: "hard",
		price_range: "high",
		description: "Elegant Victorian era woman with dress and accessories",
		image_url: "/images/victorian.jpg",
		tags: ["elegant", "dress", "19th century", "corset"],
		materials: [
			{ material: "Victorian dress", quantity: "1" },
			{ material: "Parasol", quantity: "1" },
			{ material: "Gloves", quantity: "1 pair" },
		],
	},

	// HUMOUR - SUPPLEMENT
	{
		id: 39,
		name: "Giant Baby",
		category: "funny",
		difficulty: "medium",
		price_range: "medium",
		description: "Oversized baby with diaper and pacifier",
		image_url: "/images/costumes/baby.jpg",
		tags: ["oversized", "diaper", "funny", "pacifier"],
		materials: [
			{ material: "Onesie", quantity: "1" },
			{ material: "Giant pacifier", quantity: "1" },
			{ material: "Baby bonnet", quantity: "1" },
		],
	},
	{
		id: 40,
		name: "Where's Waldo",
		category: "funny",
		difficulty: "easy",
		price_range: "low",
		description: "The iconic striped shirt and hat character",
		image_url: "/images/costumes/waldo.jpg",
		tags: ["stripes", "book", "search", "iconic"],
		materials: [
			{ material: "Striped shirt", quantity: "1" },
			{ material: "Blue pants", quantity: "1" },
			{ material: "Bobble hat", quantity: "1" },
		],
	},

	// PERSONNAGES DE FILMS CULTES
	{
		id: 41,
		name: "Ghostbuster",
		category: "movie",
		difficulty: "medium",
		price_range: "medium",
		description: "Paranormal investigator with proton pack",
		image_url: "/images/costumes/ghostbuster.jpg",
		tags: ["proton pack", "ghost", "80s", "classic"],
		materials: [
			{ material: "Jumpsuit", quantity: "1" },
			{ material: "Proton pack", quantity: "1" },
			{ material: "Ghost trap", quantity: "1" },
		],
	},
	{
		id: 42,
		name: "Indiana Jones",
		category: "movie",
		difficulty: "medium",
		price_range: "medium",
		description: "Adventurous archaeologist with hat and whip",
		image_url: "/images/costumes/indianajones.jpg",
		tags: ["adventure", "archaeologist", "whip", "fedora"],
		materials: [
			{ material: "Fedora hat", quantity: "1" },
			{ material: "Leather jacket", quantity: "1" },
			{ material: "Whip", quantity: "1" },
		],
	},

	// CREATURES ADDITIONNELLES
	{
		id: 43,
		name: "Phoenix",
		category: "fantasy",
		difficulty: "hard",
		price_range: "high",
		description: "Mythical fire bird with flame effects",
		image_url: "/images/costumes/phoenix.jpg",
		tags: ["fire", "bird", "rebirth", "mythical"],
		materials: [
			{ material: "Feather wings", quantity: "1 pair" },
			{ material: "Orange-red costume", quantity: "1" },
			{ material: "Flame effects", quantity: "set" },
		],
	},
	{
		id: 44,
		name: "Cthulhu",
		category: "horror",
		difficulty: "hard",
		price_range: "high",
		description: "Cosmic horror entity with tentacles",
		image_url: "/images/costumes/cthulhu.jpg",
		tags: ["lovecraft", "tentacles", "cosmic", "elder god"],
		materials: [
			{ material: "Tentacle mask", quantity: "1" },
			{ material: "Robes", quantity: "1" },
			{ material: "Wings", quantity: "1 pair" },
		],
	},

	// COSTUMES DE NOËL (pour plus tard)
	{
		id: 45,
		name: "Santa Claus",
		category: "holiday",
		difficulty: "easy",
		price_range: "low",
		description: "Jolly Christmas gift-bringer",
		image_url: "/images/costumes/santa.jpg",
		tags: ["christmas", "gifts", "red", "jolly"],
		materials: [
			{ material: "Red suit", quantity: "1" },
			{ material: "White beard", quantity: "1" },
			{ material: "Black boots", quantity: "1 pair" },
		],
	},
	{
		id: 46,
		name: "Gingerbread Man",
		category: "holiday",
		difficulty: "medium",
		price_range: "medium",
		description: "Sweet cookie come to life",
		image_url: "/images/costumes/gingerbread.jpg",
		tags: ["christmas", "cookie", "sweet", "holiday"],
		materials: [
			{ material: "Brown bodysuit", quantity: "1" },
			{ material: "Icing details", quantity: "set" },
			{ material: "Candy buttons", quantity: "3" },
		],
	},
];
